/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Acesso = sequelize.define('Acesso', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    pessoasId: DataTypes.INTEGER(5),
    acesso: DataTypes.DATE,
    ip: DataTypes.STRING(15),
    platform: DataTypes.STRING(150),
    accessToken: DataTypes.STRING(72),
    valid: DataTypes.BOOLEAN(1),
    //TODO  add county
    //TODO add city
    revokedOn: DataTypes.DATE,
  }, {
    tableName: 'Acesso',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Acesso.belongsTo(models.Pessoas, {
          foreignKey: 'pessoasId',              //on Acesso
          targetKey: 'id',  //foreign key  
        }); 
      }
    },
  });

  return Acesso;
};
