/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const BarracasChapeus = sequelize.define('BarracasChapeus', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    numero: DataTypes.STRING(3),
    tipo: DataTypes.STRING(254),
    subTipo: DataTypes.STRING(254),
    localizacao: DataTypes.STRING(254),
  }, {
    tableName: 'BarracasChapeus',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        BarracasChapeus.belongsTo(models.Aluguer, {
          foreignKey: 'id',              //on BarracasChapeus
          targetKey: 'barracaChapeusId',  //foreign key  
        });
        BarracasChapeus.belongsTo(models.Reservas, {
          foreignKey: 'id',              //on BarracasChapeus
          targetKey: 'barracaChapeusId',  //foreign key  
        }); 
      }
    },
  });

  return BarracasChapeus;
};
