/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Comentarios = sequelize.define('Comentarios', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    comentario: DataTypes.STRING,
  }, {
    tableName: 'Comentarios',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Comentarios.belongsTo(models.Aluguer, {
          foreignKey: 'id',              //on Comentarios
          targetKey: 'comentarioId',  //foreign key  
        });
        Comentarios.belongsTo(models.Reservas, {
          foreignKey: 'id',              //on Comentarios
          targetKey: 'comentarioId',  //foreign key  
        }); 
      }
    },
  });

  return Comentarios;
};
