/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Pago = sequelize.define('Pago', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    valor: DataTypes.FLOAT,
    pago: DataTypes.BOOLEAN,
    reservaId: DataTypes.INTEGER(11),
    comentarioId: DataTypes.INTEGER(11),
    operadorId: DataTypes.INTEGER(11),
    em: DataTypes.DATE,
  }, {
      tableName: 'Pago',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Pago.belongsTo(models.Reservas, {
            foreignKey: 'reservaId',              //on Pago
            targetKey: 'id',  //foreign key  
          });
          Pago.belongsTo(models.Comentarios, {
            foreignKey: 'comentarioId',              //on Pago
            targetKey: 'id',  //foreign key  
          });
          Pago.belongsTo(models.Pessoas, {
            foreignKey: 'operadorId',              //on Pago
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Pago;
  };
