/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Pessoas = sequelize.define('Pessoas', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    nome: DataTypes.STRING(50),
    permissao: DataTypes.STRING(50),
  }, {
    tableName: 'Pessoas',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Pessoas.belongsTo(models.Aluguer, {
          foreignKey: 'id',              //on Pessoas
          targetKey: 'operadorId',  //foreign key  
        });
        Pessoas.belongsTo(models.Reservas, {
          foreignKey: 'id',              //on Pessoas
          targetKey: 'operadorId',  //foreign key  
        }); 
      }
    },
  });

  return Pessoas;
};
