/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Preco = sequelize.define('Preco', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    tipo: DataTypes.ENUM('Barraca','Chapeu'),
    subTipo: DataTypes.ENUM('Frontal','Lateral','Traseira'),
    extra: {
      type:DataTypes.STRING(254),
      allowNull:true,
    },
    duracao: DataTypes.ENUM('Manhã','Tarde','Dia','Semana','Quinzena','Mês'),
    valor: DataTypes.FLOAT,
  }, {
    tableName: 'Preco',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {     
      }
    },
  });

  return Preco;
};
