/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Reservas = sequelize.define('Reservas', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    barracaChapeusId: DataTypes.INTEGER(5),
    nome: DataTypes.STRING(254),
    dataInicio: DataTypes.DATEONLY,
    dataFim: DataTypes.DATEONLY,
    valor: DataTypes.FLOAT,
    comentarioId: DataTypes.INTEGER(10),
    operadorId: DataTypes.INTEGER(11),
    registo: DataTypes.DATE,
    del: BOOLEAN,
  }, {
    tableName: 'Reservas',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Reservas.belongsTo(models.BarracasChapeus, {
          foreignKey: 'barracaChapeusId',              //on Reservas
          targetKey: 'id',  //foreign key  
        });
        Reservas.belongsTo(models.Comentarios, {
          foreignKey: 'comentarioId',              //on Reservas
          targetKey: 'id',  //foreign key  
        });
        Reservas.belongsTo(models.Pessoas, {
          foreignKey: 'operadorId',              //on Reservas
          targetKey: 'id',  //foreign key  
        }); 
      }
    },
  });

  return Reservas;
};
